# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 79622fcbb428ad80acd7ac601451794089461541832b76e1f9c0182fc2d986668ef56fdbf7604aa2b0ecb97d2a14464525e5b7a666e3dcbddab28c490ad60300

test:
  secret_key_base: 02e93c101a6f5c17fee300d39e02fc893495fc340973f344f1f6c5e779d11b5442f457bb3c324e15e00f4b062708776a6923561858bfa067ba333b74cd21a3dd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
